name: Sync branch
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    name: Update develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: dev
          token: ${{ secrets.GH_ACT_PAT }}
          force: false
