name: Sync branch
on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    name: Update develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: dev
          token: ${{ secrets.GH_ACT_PAT }}
          force: false
